### ISSUE TITLE
recipe.js img태그 속성에 alt 추가 요망

### ISSUE THREAD

**Issue by Yehoonn** [dlehdrb128/NongDam_Project#60]
![캡처](https://user-images.githubusercontent.com/71740425/194187069-8b6ffb6d-642b-4b90-b60f-890dbe49d7ad.PNG)
recipe.js img태그 속성에 alt 추가 요망

@geunsoo96

**Comment by geunsoo96** [comment]
recipe 페이지 이미지 태그 alt 전부 추가했습니다~
